name: build

on: [push]

jobs:
    build:
        runs-on: macos-latest
        steps:
            - run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

            - uses: actions/checkout@v2
              with:
                  submodules: "recursive"

            - run: just download-restic

            - run: npm install

            - run: npm install dmg-license

            - run: CSC_IDENTITY_AUTO_DISCOVERY=false npm run dist-mac

            - run: rm -rf node_modules

            - uses: docker-practice/actions-setup-docker@master

            - run: docker run --rm -i --env ELECTRON_CACHE="/root/.cache/electron" --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules -v ~/.cache/electron:/root/.cache/electron -v ~/.cache/electron-builder:/root/.cache/electron-builder electronuserland/builder:wine bash -c 'npm install; npm run build; npm run dist'

            - uses: actions/upload-artifact@v2
              with:
                  name: "backup-1.0.0.AppImage"
                  path: "output/backup-1.0.0.AppImage"

            - uses: actions/upload-artifact@v2
              with:
                  name: "backup_1.0.0_amd64.snap"
                  path: "output/backup_1.0.0_amd64.snap"

            - uses: actions/upload-artifact@v2
              with:
                  name: "backup Setup 1.0.0.exe"
                  path: "output/backup Setup 1.0.0.exe"

            - uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: |
                      output/backup-1.0.0.AppImage
                      output/backup_1.0.0_amd64.snap
                      output/backup Setup 1.0.0.exe
