name: build

on: [push, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

            - uses: actions/checkout@v2
              with:
                  submodules: "recursive"

            - run: just download-restic

            - run: docker run --rm -i -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules electronuserland/builder:wine bash -c 'npm install; npm run build; npm run dist'

            - uses: actions/upload-artifact@v2
              with:
                  name: "backup-1.0.0.AppImage"
                  path: "output/backup-1.0.0.AppImage"

            - uses: actions/upload-artifact@v2
              with:
                  name: "backup_1.0.0_amd64.snap"
                  path: "output/backup_1.0.0_amd64.snap"

            - uses: actions/upload-artifact@v2
              with:
                  name: "backup Setup 1.0.0.exe"
                  path: "output/backup Setup 1.0.0.exe"

            - run: docker run --rm -i -v ${PWD}:/project debian:latest bash -c "rm -rf /project/*"
