name: build

on: [push, workflow_dispatch]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: "recursive"

            - run: docker run --user 0:$(id -g) --rm -i -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules electronuserland/builder:wine bash -c 'npm install; npm run build; npm run dist'

            - uses: actions/upload-artifact@v2
              with:
                  name: "backup-1.0.0.AppImage"
                  path: "bin/backup-1.0.0.AppImage"

            - uses: actions/upload-artifact@v2
              with:
                  name: "backup_1.0.0_amd64.snap"
                  path: "bin/backup_1.0.0_amd64.snap"

            - uses: actions/upload-artifact@v2
              with:
                  name: "backup Setup 1.0.0.exe"
                  path: "bin/backup Setup 1.0.0.exe"
