name: build

on: [push, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

            - uses: actions/checkout@v3
              with:
                  submodules: "recursive"

            - run: npm install
            - run: npm run build-frontend
            - run: npm run build-backend
