name: build

on: [push]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: "recursive"

            - uses: docker-practice/actions-setup-docker@master

            - run: docker run --rm -i --env ELECTRON_CACHE="/root/.cache/electron" --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules -v ~/.cache/electron:/root/.cache/electron -v ~/.cache/electron-builder:/root/.cache/electron-builder electronuserland/builder:wine bash -c 'npm install; npm run build; npm run dist'

            - uses: actions/upload-artifact@v2
              with:
                  name: "backup-1.0.0.AppImage"
                  path: "bin/backup-1.0.0.AppImage"

            - uses: actions/upload-artifact@v2
              with:
                  name: "backup_1.0.0_amd64.snap"
                  path: "bin/backup_1.0.0_amd64.snap"

            - uses: actions/upload-artifact@v2
              with:
                  name: "backup Setup 1.0.0.exe"
                  path: "bin/backup Setup 1.0.0.exe"
