name: linter

on: [push]

jobs:
    prettier:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - run: npm install
            - run: npx run lint
