on: [push]

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3.0.0
              with:
                  node-version: "16"
            - run: npm install
            - run: ./node_modules/prettier/bin-prettier.js --check .
