name: prettier

on: [push]

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm install
            - run: ./node_modules/prettier/bin-prettier.js --check .
